const fs = require('fs');
let text = fs.readFileSync('src/pages/area-layanan/bore-pile/[kota].astro', 'utf8');

const imports = "import ComparisonSection from '../../../components/ui/ComparisonSection.astro';\nimport ServiceFeatures from '../../../components/ui/ServiceFeatures.astro';\n";
if(!text.includes('ComparisonSection')) {
  text = text.replace("import ArticleList from", imports + "import ArticleList from");
}

const featRegex = /<!-- SECTION 6: Keunggulan[\s\S]*?<!-- ================================================ -->\s*<!-- SECTION 7:/;
const icon1 = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>';
const icon2 = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="7"></circle><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"></polyline></svg>';
const icon3 = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="16" height="20" x="4" y="2" rx="2" ry="2"></rect><path d="M12 18h.01"></path><path d="M8 18h.01"></path><path d="M16 18h.01"></path><path d="M12 14h.01"></path><path d="M8 14h.01"></path><path d="M16 14h.01"></path><path d="M12 10h.01"></path><path d="M8 10h.01"></path><path d="M16 10h.01"></path></svg>';

const newFeat = `<!-- SECTION 6: Keunggulan -->\n  <ServiceFeatures\n    title={\`Keunggulan Jasa Bore Pile Aseven Pile di \${cityData.name}\`}\n    features={[\n      { title: "Minim Getaran & Aman", desc: \`Mesin bor kami dirancang bekerja tanpa menimbulkan getaran keras. Sangat aman diaplikasikan di lingkungan padat penduduk \${cityData.name} tanpa merusak tembok rumah tetangga.\`, iconRawSvg: \`${icon1}\` },\n      { title: "Berpengalaman", desc: "Tim kami sudah berpengalaman dalam pekerjaan pondasi, khususnya bore pile, dan terbiasa menangani berbagai kondisi tanah di lapangan.", iconRawSvg: \`${icon2}\` },\n      { title: "Komitmen Kualitas", desc: "Layanan yang dihasilkan mengutamakan kualitas dan dikerjakan sesuai prosedur, spesifikasi yang disepakati, serta Standar Nasional Indonesia (SNI).", iconRawSvg: \`${icon3}\` }\n    ]}\n  />\n\n  <!-- ================================================ -->\n  <!-- SECTION 7:`;

text = text.replace(featRegex, newFeat);

const vsRegex = /<!-- SECTION 7: Bore Pile Mesin vs Tiang Pancang[\s\S]*?<!-- ================================================ -->\s*<!-- SECTION 8:/;
const newVs = `<!-- SECTION 7: Bore Pile Mesin vs Tiang Pancang -->\n  <ComparisonSection\n    title={\`Bore Pile Mesin vs Tiang Pancang di \${cityData.name}\`}\n    description={\`Bingung antara pondasi bor (bore pile) atau tiang pancang? Berikut bedanya, disesuaikan dengan kondisi lapangan di \${cityData.name}:\`}\n    primaryTitle="Bore Pile Mesin"\n    primaryDesc={\`Bore pile mesin merupakan metode <em>cast in-situ</em>, yaitu lubang dibor terlebih dahulu di lokasi, kemudian diisi besi tulangan dan dicor beton langsung di tempat. Karena tidak melalui proses pemancangan, getaran dan suara yang dihasilkan sangat minim sehingga aman diterapkan di lingkungan padat bangunan seperti \${cityData.name}. Diameternya fleksibel, mulai 30 hingga 80 cm, dengan kedalaman mencapai 30 meter tergantung kondisi tanah. Mini crane yang kami gunakan dirancang untuk masuk ke gang sempit dan jalan terbatas, sehingga bore pile dapat dikerjakan di lokasi yang tidak dapat dijangkau truk besar. Untuk area yang benar-benar sempit, metode alternatifnya adalah <a href="/area-layanan/strauss-pile/\${cityData.slug}">Strauss Pile</a> yang menggunakan tenaga manual.\`}\n    secondaryTitle="Tiang Pancang (Paku Bumi)"\n    secondaryDesc="Tiang pancang merupakan kebalikannya. Beton dicetak di pabrik secara <em>precast</em>, lalu dipancang ke dalam tanah menggunakan palu berat. Metode ini lebih cepat dan seringkali lebih ekonomis untuk tanah lunak, serta mutu betonnya lebih terkontrol karena dicetak di pabrik. Namun, ada konsekuensi yang perlu dipertimbangkan. Getaran yang ditimbulkan cukup besar sehingga berisiko meretakkan dinding bangunan tua di sekitarnya, suaranya bising, dan alat pancang membutuhkan akses jalan lebar minimal 4 sampai 5 meter sehingga tidak dapat masuk ke gang sempit. Tiang pancang baru menjadi pertimbangan apabila lokasi jauh dari bangunan tetangga, akses jalan lebar, dan tanahnya lunak homogen."\n    conclusion={\`<strong>Kesimpulan:</strong> Untuk mayoritas proyek di <strong>\${cityData.name}</strong>, terutama ruko, rumah tinggal, dan gedung bertingkat di lingkungan padat, bore pile mesin hampir selalu menjadi pilihan yang lebih aman. Bukan karena lebih murah, sebab kadang justru lebih mahal, tetapi karena tidak berisiko merusak bangunan tetangga dan dapat masuk ke lokasi yang tidak dapat diakses alat pancang. Apabila masih ragu, tim kami dapat melakukan survei lapangan untuk menilai kondisi tanah dan akses, lalu merekomendasikan metode yang paling efisien untuk proyek Anda.\`}\n  />\n\n  <!-- ================================================ -->\n  <!-- SECTION 8:`;

text = text.replace(vsRegex, newVs);

fs.writeFileSync('src/pages/area-layanan/bore-pile/[kota].astro', text);
