const fs = require('fs');
let text = fs.readFileSync('src/pages/area-layanan/strauss-pile/[kota].astro', 'utf8');

// Replace the features array
const oldFeatures = `features={[
      { title: "Minim Getaran & Aman", desc: \`Mesin bor kami dirancang bekerja tanpa menimbulkan getaran keras. Sangat aman diaplikasikan di lingkungan padat penduduk \${cityData.name} tanpa merusak tembok rumah tetangga.\`, iconRawSvg: \`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>\` },
      { title: "Berpengalaman", desc: "Tim kami sudah berpengalaman dalam pekerjaan pondasi, khususnya strauss pile, dan terbiasa menangani berbagai kondisi tanah di lapangan.", iconRawSvg: \`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="7"></circle><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"></polyline></svg>\` },
      { title: "Komitmen Kualitas", desc: "Layanan yang dihasilkan mengutamakan kualitas dan dikerjakan sesuai prosedur, spesifikasi yang disepakati, serta Standar Nasional Indonesia (SNI).", iconRawSvg: \`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="16" height="20" x="4" y="2" rx="2" ry="2"></rect><path d="M12 18h.01"></path><path d="M8 18h.01"></path><path d="M16 18h.01"></path><path d="M12 14h.01"></path><path d="M8 14h.01"></path><path d="M16 14h.01"></path><path d="M12 10h.01"></path><path d="M8 10h.01"></path><path d="M16 10h.01"></path></svg>\` }
    ]}`;

const newFeatures = `features={[
      { title: "Tanpa Alat Berat", desc: "Strauss pile kami dikerjakan sepenuhnya dengan tenaga manusia dan alat bor ringkas. Tidak ada mesin berat yang perlu masuk ke lokasi. Cukup diangkut mobil pick-up, dan bisa dikerjakan di dalam ruangan atau gang yang lebarnya kurang dari 1,5 meter.", iconRawSvg: \`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>\` },
      { title: "Tanpa Getaran & Tanpa Suara", desc: "Karena tidak menggunakan mesin, strauss pile tidak menimbulkan getaran maupun suara bising. Sangat aman untuk proyek renovasi rumah di perumahan padat, atau pagar yang berbatasan langsung dengan bangunan tetangga.", iconRawSvg: \`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 2v2"></path><path d="M11 20v2"></path><path d="M4.22 4.22l1.42 1.42"></path><path d="M18.36 18.36l1.42 1.42"></path><path d="M2 11h2"></path><path d="M20 11h2"></path><path d="M4.22 17.78l1.42-1.42"></path><path d="M18.36 5.64l1.42-1.42"></path></svg>\` },
      { title: "Berpengalaman", desc: "Tim kami sudah berpengalaman sejak 2015 dalam pekerjaan pondasi manual, khususnya strauss pile, dan terbiasa menangani berbagai kondisi tanah di lapangan, termasuk tanah berair dan akses yang sangat sempit.", iconRawSvg: \`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="7"></circle><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"></polyline></svg>\` },
      { title: "Komitmen Kualitas", desc: "Layanan yang dihasilkan mengutamakan kualitas dan dikerjakan sesuai prosedur, spesifikasi yang disepakati, serta Standar Nasional Indonesia (SNI).", iconRawSvg: \`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="16" height="20" x="4" y="2" rx="2" ry="2"></rect><path d="M12 18h.01"></path><path d="M8 18h.01"></path><path d="M16 18h.01"></path><path d="M12 14h.01"></path><path d="M8 14h.01"></path><path d="M16 14h.01"></path><path d="M12 10h.01"></path><path d="M8 10h.01"></path><path d="M16 10h.01"></path></svg>\` }
    ]}`;

text = text.replace(oldFeatures, newFeatures);
fs.writeFileSync('src/pages/area-layanan/strauss-pile/[kota].astro', text);
